apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kong/kubernetes-ingress-controller.git
    targetRevision: HEAD
    path: deploy/manifests/base
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated: {}
