apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: github.com/kong/kubernetes-ingress-controller/deploy/manifests/base
    targetRevision: HEAD
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated: {}
